// flow-typed signature: c3a68026c0b53318c65a252945ad9bd4
// flow-typed version: <<STUB>>/@commitlint/config-conventional_v^6.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-conventional'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-conventional' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@commitlint/config-conventional/index' {
  declare module.exports: $Exports<'@commitlint/config-conventional'>
}
declare module '@commitlint/config-conventional/index.js' {
  declare module.exports: $Exports<'@commitlint/config-conventional'>
}
